--[[ Generated by the Kthura Map Editor
     Generated: 17 Feb 2018; 17:16:39


     This file has been set up as an import



]]



local Kthura = {}
local Meta = {}
Meta["AltEncounterTune"] = ""
Meta["Arena"] = ""
Meta["Foes1"] = ""
Meta["Foes2"] = ""
Meta["Foes3"] = ""
Meta["Foes_NG+"] = ""
Meta["MaxEnc"] = ""
Meta["Music"] = "music/dungeon/stormfront.mp3"
Meta["NamedZones"] = ""
Meta["NoEncZones"] = ""
Meta["NoSaveZones"] = ""
Meta["RandomItems"] = ""
Meta["RandomItems_NG+"] = ""
Meta["Title"] = "Beaufort Forest"



local MapObjects = {}
local BM_Grid = {}
local TagMap = {}
local LabelMap = {}
local KNO
Kthura = { MapObjects=MapObjects, Grid=BM_Grid, TagMap = TagMap, LabelMap=LabelMap, Meta=Meta }
MapObjects["#001"] = {}
LabelMap["#001"] = {}
TagMap["#001"] = {}

-- #001
	BM_Grid["#001"] = "32x32"
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = -20, y = 102 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/TEXTURES/TREES/SPAR.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = -9, y = 106 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/TEXTURES/TREES/SPAR.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 7, y = 112 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/TEXTURES/TREES/SPAR.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 26, y = 111 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/TEXTURES/TREES/SPAR.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 34, y = 108 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/TEXTURES/TREES/SPAR.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 47, y = 98 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/TEXTURES/TREES/SPAR.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 57, y = 85 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/TEXTURES/TREES/SPAR.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 61, y = 84 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/TEXTURES/TREES/SPAR.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 84, y = 73 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/TEXTURES/TREES/SPAR.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 103, y = 58 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/TEXTURES/TREES/SPAR.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 110, y = 56 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/TEXTURES/TREES/SPAR.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 133, y = 51 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/TEXTURES/TREES/SPAR.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 146, y = 51 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/TEXTURES/TREES/SPAR.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 169, y = 56 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/TEXTURES/TREES/SPAR.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 182, y = 59 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/TEXTURES/TREES/SPAR.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 204, y = 65 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/TEXTURES/TREES/SPAR.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 226, y = 68 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/TEXTURES/TREES/SPAR.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 238, y = 68 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/TEXTURES/TREES/SPAR.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 255, y = 69 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/TEXTURES/TREES/SPAR.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 279, y = 68 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/TEXTURES/TREES/SPAR.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 294, y = 64 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/TEXTURES/TREES/SPAR.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 317, y = 64 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/TEXTURES/TREES/SPAR.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 337, y = 67 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/TEXTURES/TREES/SPAR.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 365, y = 79 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/TEXTURES/TREES/SPAR.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 388, y = 80 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/TEXTURES/TREES/SPAR.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 419, y = 85 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/TEXTURES/TREES/SPAR.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 442, y = 95 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/TEXTURES/TREES/SPAR.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 458, y = 100 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/TEXTURES/TREES/SPAR.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 481, y = 111 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/TEXTURES/TREES/SPAR.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 508, y = 120 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/TEXTURES/TREES/SPAR.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 522, y = 122 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/TEXTURES/TREES/SPAR.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 552, y = 126 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/TEXTURES/TREES/SPAR.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 574, y = 124 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/TEXTURES/TREES/SPAR.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 610, y = 112 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/TEXTURES/TREES/SPAR.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 617, y = 104 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/TEXTURES/TREES/SPAR.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 621, y = 98 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/TEXTURES/TREES/SPAR.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 733, y = 102 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/TEXTURES/TREES/SPAR.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 740, y = 117 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/TEXTURES/TREES/SPAR.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 722, y = 116 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/TEXTURES/TREES/SPAR.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 709, y = 111 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/TEXTURES/TREES/SPAR.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 690, y = 106 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/TEXTURES/TREES/SPAR.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 673, y = 104 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/TEXTURES/TREES/SPAR.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 656, y = 105 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/TEXTURES/TREES/SPAR.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 649, y = 105 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/TEXTURES/TREES/SPAR.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 630, y = 113 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/TEXTURES/TREES/SPAR.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = -14, y = 225 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/TEXTURES/TREES/SPAR.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = -7, y = 227 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/TEXTURES/TREES/SPAR.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = -5, y = 229 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/TEXTURES/TREES/SPAR.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 6, y = 237 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/TEXTURES/TREES/SPAR.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 13, y = 243 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/TEXTURES/TREES/SPAR.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 16, y = 246 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/TEXTURES/TREES/SPAR.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 21, y = 252 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/TEXTURES/TREES/SPAR.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 28, y = 257 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/TEXTURES/TREES/SPAR.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 39, y = 264 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/TEXTURES/TREES/SPAR.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 48, y = 266 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/TEXTURES/TREES/SPAR.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 69, y = 273 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/TEXTURES/TREES/SPAR.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 89, y = 279 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/TEXTURES/TREES/SPAR.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 103, y = 281 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/TEXTURES/TREES/SPAR.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 113, y = 282 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/TEXTURES/TREES/SPAR.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 124, y = 284 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/TEXTURES/TREES/SPAR.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 143, y = 287 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/TEXTURES/TREES/SPAR.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 160, y = 289 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/TEXTURES/TREES/SPAR.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 178, y = 292 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/TEXTURES/TREES/SPAR.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 194, y = 300 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/TEXTURES/TREES/SPAR.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 218, y = 312 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/TEXTURES/TREES/SPAR.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 269, y = 338 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/TEXTURES/TREES/SPAR.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 226, y = 313 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/TEXTURES/TREES/SPAR.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 236, y = 318 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/TEXTURES/TREES/SPAR.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 260, y = 333 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/TEXTURES/TREES/SPAR.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 273, y = 346 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/TEXTURES/TREES/SPAR.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 298, y = 364 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/TEXTURES/TREES/SPAR.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 319, y = 386 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/TEXTURES/TREES/SPAR.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 334, y = 408 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/TEXTURES/TREES/SPAR.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 351, y = 433 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/TEXTURES/TREES/SPAR.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 368, y = 457 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/TEXTURES/TREES/SPAR.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 361, y = 454 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/TEXTURES/TREES/SPAR.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 348, y = 438 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/TEXTURES/TREES/SPAR.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 331, y = 417 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/TEXTURES/TREES/SPAR.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 322, y = 410 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/TEXTURES/TREES/SPAR.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 305, y = 395 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/TEXTURES/TREES/SPAR.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 283, y = 380 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/TEXTURES/TREES/SPAR.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 257, y = 362 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/TEXTURES/TREES/SPAR.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 230, y = 349 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/TEXTURES/TREES/SPAR.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 222, y = 344 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/TEXTURES/TREES/SPAR.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 739, y = 107 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/TEXTURES/TREES/SPAR.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 751, y = 133 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/TEXTURES/TREES/SPAR.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 757, y = 144 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/TEXTURES/TREES/SPAR.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 762, y = 162 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/TEXTURES/TREES/SPAR.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 759, y = 184 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/TEXTURES/TREES/SPAR.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 759, y = 192 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/TEXTURES/TREES/SPAR.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 760, y = 190 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/TEXTURES/TREES/SPAR.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 774, y = 170 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/TEXTURES/TREES/SPAR.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 786, y = 159 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/TEXTURES/TREES/SPAR.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 800, y = 152 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/TEXTURES/TREES/SPAR.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 828, y = 146 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/TEXTURES/TREES/SPAR.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 594, y = 266 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/TEXTURES/TREES/SPAR.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 868, y = 269 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/TEXTURES/TREES/SPAR.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 800, y = 800 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#001"][#MapObjects["#001"]+1] = KNO
		KNO["KIND"] = "Exit"
		KNO["COORD"] = { x = 243, y = 137 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = "Start"
			TagMap["#001"]["Start"] = KNO
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = ""
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 127, g = 127, b = 255 } 
		KNO["IMPASSIBLE"] = false
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0

-- #001



return Kthura
