--[[ Generated by the Kthura Map Editor
     Generated: 04 Jan 2018; 17:13:18


     This file has been set up as an import



]]



local Kthura = {}
local Meta = {}



local MapObjects = {}
local BM_Grid = {}
local TagMap = {}
local LabelMap = {}
local KNO
Kthura = { MapObjects=MapObjects, Grid=BM_Grid, TagMap = TagMap, LabelMap=LabelMap, Meta=Meta }
MapObjects["#000"] = {}
LabelMap["#000"] = {}
TagMap["#000"] = {}

-- #000
	BM_Grid["#000"] = "32x32"
	KNO={}
	MapObjects["#000"][#MapObjects["#000"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 176, y = 128 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/MENU/ITEM1.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 255, g = 255, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#000"][#MapObjects["#000"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 144, y = 192 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/MENU/ITEM2.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 255, g = 255, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#000"][#MapObjects["#000"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 176, y = 288 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/MENU/ITEM3.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 255, g = 255, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#000"][#MapObjects["#000"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 176, y = 384 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/MENU/ITEM4.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 255, g = 255, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#000"][#MapObjects["#000"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 176, y = 480 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/MENU/ITEM5.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 255, g = 255, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#000"][#MapObjects["#000"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 176, y = 576 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/MENU/ITEM6.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 255, g = 255, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#000"][#MapObjects["#000"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 496, y = 160 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/NETWORK/ANNA.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 255, g = 255, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#000"][#MapObjects["#000"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 816, y = 224 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/NETWORK/GJ.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 255, g = 255, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#000"][#MapObjects["#000"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 496, y = 256 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/PORTRET/RYANNA/GENERAL.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 255, g = 255, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#000"][#MapObjects["#000"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 624, y = 256 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/SKILLS/1.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 255, g = 255, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#000"][#MapObjects["#000"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 752, y = 256 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/SKILLS/2.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 255, g = 255, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#000"][#MapObjects["#000"]+1] = KNO
		KNO["KIND"] = "Obstacle"
		KNO["COORD"] = { x = 880, y = 256 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 0, height = 0 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/SKILLS/3.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 255, g = 255, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0
	KNO={}
	MapObjects["#000"][#MapObjects["#000"]+1] = KNO
		KNO["KIND"] = "TiledArea"
		KNO["COORD"] = { x = 0, y = 0 } 
		KNO["INSERT"] = { x = 0, y = 0 } 
		KNO["ROTATION"] = 0
		KNO["SIZE"] = { width = 1184, height = 992 } 
		KNO["TAG"] = ""
		KNO["LABELS"] = ""
		KNO["DOMINANCE"] = 20
		KNO["TEXTURE"] = "GFX/SYSTEM/CONSOLE.PNG"
		KNO["CURRENTFRAME"] = 0
		KNO["FRAMESPEED"] = -1
		KNO["ALPHA"] = 1.0000000000000000
		KNO["VISIBLE"] = true
		KNO["COLOR"] = { r = 255, g = 255, b = 255 } 
		KNO["IMPASSIBLE"] = true
		KNO["FORCEPASSIBLE"] = false
		KNO["SCALE"] = { x = 1000, y = 1000 } 
		KNO["BLEND"] = 0

-- #000



return Kthura
