--[[ Generated by the Kthura Map Editor
     Generated: 27 Apr 2018; 14:59:14


     This file has been set up as an import



]]



local Kthura = {}
local Meta = {}
Meta["AltEncounterTune"] = ""
Meta["Arena"] = ""
Meta["Foes1"] = ""
Meta["Foes2"] = ""
Meta["Foes3"] = ""
Meta["Foes_NG+"] = ""
Meta["MaxEnc"] = ""
Meta["Music"] = ""
Meta["NamedZones"] = ""
Meta["NoEncZones"] = ""
Meta["NoSaveZones"] = ""
Meta["RandomItems"] = ""
Meta["RandomItems_NG+"] = ""
Meta["Title"] = "The city of Windville"



local MapObjects = {}
local BM_Grid = {}
local TagMap = {}
local LabelMap = {}
local KNO
Kthura = { MapObjects=MapObjects, Grid=BM_Grid, TagMap = TagMap, LabelMap=LabelMap, Meta=Meta }
MapObjects["Outside"] = {}
LabelMap["Outside"] = {}
TagMap["Outside"] = {}

-- Outside
	BM_Grid["Outside"] = "32x32"

-- Outside



return Kthura
