--[[
**********************************************
  
  SCYNDI.lua
  (c) Jeroen Broks, 2018, All Rights Reserved.
  
  This file contains material that is related 
  to a storyline that is which is strictly
  copyrighted to Jeroen Broks.
  
  This file may only be used in an unmodified
  form with an unmodified version of the 
  software this file belongs to.
  
  You may use this file for your study to see
  how I solved certain things in the creation
  of this project to see if you find valuable
  leads for the creation of your own.
  
  Mostly this file comes along with a project
  that is for most part released under an
  open source license and that means that if
  you use that code with this file removed
  from it, you can use it under that license.
  Please check out the other files to find out
  which license applies.
  This file comes 'as-is' and in no possible
  way the author can be held responsible of
  any form of damages that may occur due to 
  the usage of this file
  
  
 **********************************************
 
version: 18.12.05
]]
-- File generated by MyData on Wednesday 5/12/2018
-- License: This file contains data from the Phantasar Universe and is therefore property of Jeroen Broks and may NOT be used for your own ends.

local ret={
	["Slot1"] = "",
	["Slot10"] = "",
	["Slot11"] = "",
	["Slot12"] = "",
	["Slot13"] = "ITM_ROCK",
	["Slot14"] = "ITM_ICICLE",
	["Slot15"] = "ITM_FAN",
	["Slot16"] = "ITM_SAUERKRAUT",
	["Slot17"] = "",
	["Slot18"] = "",
	["Slot19"] = "",
	["Slot2"] = "",
	["Slot20"] = "",
	["Slot3"] = "",
	["Slot4"] = "",
	["Slot5"] = "",
	["Slot6"] = "",
	["Slot7"] = "",
	["Slot8"] = "",
	["Slot9"] = "",
	["Title"] = "Scorpion & Co.",
}

return ret

