-- This file has be generated by Tricky's MyData
-- 04 May 2018; 21:27:09
-- License: This file is property of Jeroen Broks and may NOT be used for your own ends.



local ret = {
	["ARRIVE_WINDVILLE"] = {
		["Description"] = "Arrive in Windville",
		["Icon"] = "*DEFAULT*",
		["NewGamePlus"] = true,
		["NormalGame"] = true,
		["Show"] = "Always",
		["Title"] = "The answer, my friend, is blowing in the wind",
		["Type"] = "Bronze",
		["skill1"] = true,
		["skill2"] = true,
		["skill3"] = true},
	["FISH_5"] = {
		["Description"] = "Catch 5 different kinds of fish (trash included, monsters are not).",
		["Icon"] = "*DEFAULT*",
		["NewGamePlus"] = true,
		["NormalGame"] = true,
		["Show"] = "Always",
		["Title"] = "Rock and pool, it's nice and cool, so juicy sweet.",
		["Type"] = "Gold",
		["skill1"] = true,
		["skill2"] = true,
		["skill3"] = true},
	["FISH_ALL"] = {
		["Description"] = "Catch at least 1 of every kind of fish (this includes trash, but excludes monsters)",
		["Icon"] = "*DEFAULT*",
		["NewGamePlus"] = true,
		["NormalGame"] = true,
		["Show"] = "Always",
		["Title"] = "I only wish to catch fish, so juicy sweet",
		["Type"] = "Platinum",
		["skill1"] = true,
		["skill2"] = true,
		["skill3"] = true},
	["GAMECOMPLETESKILL1"] = {
		["Description"] = "Complete the game in easy mode",
		["Icon"] = "*DEFAULT*",
		["NewGamePlus"] = true,
		["NormalGame"] = true,
		["Show"] = "Always",
		["Title"] = "Get away from me, creep!",
		["Type"] = "Bronze",
		["skill1"] = true,
		["skill2"] = false,
		["skill3"] = false},
	["GAMECOMPLETESKILL2"] = {
		["Description"] = "Complete the game in casual mode",
		["Icon"] = "*DEFAULT*",
		["NewGamePlus"] = true,
		["NormalGame"] = true,
		["Show"] = "Always",
		["Title"] = "I beat this game, and all I got was this lousy T-shirt",
		["Type"] = "Silver",
		["skill1"] = false,
		["skill2"] = true,
		["skill3"] = false},
	["GAMECOMPLETESKILL3"] = {
		["Description"] = "Complete the game in the hard mode",
		["Icon"] = "*DEFAULT*",
		["NewGamePlus"] = true,
		["NormalGame"] = true,
		["Show"] = "Always",
		["Title"] = "Tod ist mein leben",
		["Type"] = "Platinum",
		["skill1"] = false,
		["skill2"] = false,
		["skill3"] = true},
	["SCEN_TRANSFORM1"] = {
		["Description"] = "Unlock Ryanna's first transformation",
		["Icon"] = "*DEFAULT*",
		["NewGamePlus"] = true,
		["NormalGame"] = true,
		["Show"] = "Always",
		["Title"] = "Transformer! Ryanna in disguise",
		["Type"] = "Bronze",
		["skill1"] = true,
		["skill2"] = true,
		["skill3"] = true}}



-- Got all data, let's now return it!
return ret
