--[[
**********************************************
  
  FishSpot.lua
  (c) Jeroen Broks, 2018, All Rights Reserved.
  
  This file contains material that is related 
  to a storyline that is which is strictly
  copyrighted to Jeroen Broks.
  
  This file may only be used in an unmodified
  form with an unmodified version of the 
  software this file belongs to.
  
  You may use this file for your study to see
  how I solved certain things in the creation
  of this project to see if you find valuable
  leads for the creation of your own.
  
  Mostly this file comes along with a project
  that is for most part released under an
  open source license and that means that if
  you use that code with this file removed
  from it, you can use it under that license.
  Please check out the other files to find out
  which license applies.
  This file comes 'as-is' and in no possible
  way the author can be held responsible of
  any form of damages that may occur due to 
  the usage of this file
  
  
 **********************************************
 
version: 18.12.13
]]
-- File generated by MyData on Thursday 13/12/2018
-- License: << No License information present >>


local ret = {
	["BEAUFORT"] = {
		["Arena"] = "",
		["Description"] = "A nice place to learn the trade of fishing",
		["Fish1"] = "ZZZ_OLDSHOE",
		["Fish10"] = "ZZZ_RUSTYCAN",
		["Fish2"] = "ZZZ_RUSTYCAN",
		["Fish3"] = "PIRANHA",
		["Fish4"] = "PIRANHA",
		["Fish5"] = "TROUT",
		["Fish6"] = "-",
		["Fish7"] = "-",
		["Fish8"] = "-",
		["Fish9"] = "ZZZ_OLDSHOE",
		["Monster1"] = "-",
		["Monster10"] = "-",
		["Monster2"] = "-",
		["Monster3"] = "-",
		["Monster4"] = "-",
		["Monster5"] = "-",
		["Monster6"] = "-",
		["Monster7"] = "-",
		["Monster8"] = "-",
		["Monster9"] = "-",
		["Name"] = "Befeaurt Forest Creek",

	},
	["PRIMOS"] = {
		["Arena"] = "ZZZ_FishingSpot.png",
		["Description"] = "The water in Primos has very nice kinds of fish",
		["Fish1"] = "ZZZ_OLDTIRE",
		["Fish10"] = "-",
		["Fish2"] = "NEONTETRA",
		["Fish3"] = "RAINBOWTROUT",
		["Fish4"] = "LOBSTER",
		["Fish5"] = "RAINBOWTROUT",
		["Fish6"] = "ZZZ_RUSTYCAN",
		["Fish7"] = "-",
		["Fish8"] = "-",
		["Fish9"] = "-",
		["Monster1"] = "-",
		["Monster10"] = "-",
		["Monster2"] = "-",
		["Monster3"] = "-",
		["Monster4"] = "-",
		["Monster5"] = "-",
		["Monster6"] = "-",
		["Monster7"] = "-",
		["Monster8"] = "-",
		["Monster9"] = "-",
		["Name"] = "Primos",

	},
	["PRIMOSTUNNEL"] = {
		["Arena"] = "ZZZ_FishingSpot.png",
		["Description"] = "Some interesting fish can be found here!",
		["Fish1"] = "MOONFISH",
		["Fish10"] = "MOONFISH",
		["Fish2"] = "NEONTETRA",
		["Fish3"] = "PIRANHA",
		["Fish4"] = "RAINBOWTROUT",
		["Fish5"] = "TROUT",
		["Fish6"] = "PIRANHA",
		["Fish7"] = "ZZZ_RUBBERDUCK",
		["Fish8"] = "NEONTETRA",
		["Fish9"] = "TROUT",
		["Monster1"] = "Reg/Snake.gini",
		["Monster10"] = "-",
		["Monster2"] = "-",
		["Monster3"] = "-",
		["Monster4"] = "-",
		["Monster5"] = "-",
		["Monster6"] = "-",
		["Monster7"] = "-",
		["Monster8"] = "-",
		["Monster9"] = "-",
		["Name"] = "Primos Tunnel Entrance",

	},
	["STARROW"] = {
		["Arena"] = "ZZZ_FishingSpot.png",
		["Description"] = "What kind of fish can be found in this place?",
		["Fish1"] = "CAVECRAB",
		["Fish10"] = "NEONTETRA",
		["Fish2"] = "CAVECRAB",
		["Fish3"] = "PIRANHA",
		["Fish4"] = "ZZZ_OLDSHOE",
		["Fish5"] = "ZZZ_RUBBERDUCK",
		["Fish6"] = "ZZZ_RUBBERDUCK",
		["Fish7"] = "ZZZ_RUSTYCAN",
		["Fish8"] = "CAVECRAB",
		["Fish9"] = "PIRANHA",
		["Monster1"] = "-",
		["Monster10"] = "-",
		["Monster2"] = "-",
		["Monster3"] = "-",
		["Monster4"] = "-",
		["Monster5"] = "-",
		["Monster6"] = "-",
		["Monster7"] = "-",
		["Monster8"] = "-",
		["Monster9"] = "-",
		["Name"] = "Starrow Subterranean River",

	},

}

return ret

