-- This file has be generated by Tricky's MyData
-- 02 Mar 2018; 20:37:16



local ret = {
	["BEAUFORT"] = {
		["Description"] = "A nice place to learn the trade of fishing",
		["Fish1"] = "ZZZ_OLDSHOE",
		["Fish10"] = "ZZZ_RUSTYCAN",
		["Fish2"] = "ZZZ_RUSTYCAN",
		["Fish3"] = "-",
		["Fish4"] = "-",
		["Fish5"] = "-",
		["Fish6"] = "-",
		["Fish7"] = "-",
		["Fish8"] = "-",
		["Fish9"] = "ZZZ_OLDSHOE",
		["Monster1"] = "-",
		["Monster10"] = "-",
		["Monster2"] = "-",
		["Monster3"] = "-",
		["Monster4"] = "-",
		["Monster5"] = "-",
		["Monster6"] = "-",
		["Monster7"] = "-",
		["Monster8"] = "-",
		["Monster9"] = "-",
		["Name"] = "Befeaurt Forest Creek"}}



-- Got all data, let's now return it!
return ret
