-- This file has be generated by Tricky's MyData
-- 16 Jun 2018; 16:57:24



local ret = {
	["BEAUFORT"] = {
		["Description"] = "A nice place to learn the trade of fishing",
		["Fish1"] = "ZZZ_OLDSHOE",
		["Fish10"] = "ZZZ_RUSTYCAN",
		["Fish2"] = "ZZZ_RUSTYCAN",
		["Fish3"] = "PIRANHA",
		["Fish4"] = "PIRANHA",
		["Fish5"] = "-",
		["Fish6"] = "-",
		["Fish7"] = "-",
		["Fish8"] = "-",
		["Fish9"] = "ZZZ_OLDSHOE",
		["Monster1"] = "-",
		["Monster10"] = "-",
		["Monster2"] = "-",
		["Monster3"] = "-",
		["Monster4"] = "-",
		["Monster5"] = "-",
		["Monster6"] = "-",
		["Monster7"] = "-",
		["Monster8"] = "-",
		["Monster9"] = "-",
		["Name"] = "Befeaurt Forest Creek"},
	["STARROW"] = {
		["Description"] = "What kind of fish can be found in this place?",
		["Fish1"] = "CAVECRAB",
		["Fish10"] = "NEONTETRA",
		["Fish2"] = "CAVECRAB",
		["Fish3"] = "PIRANHA",
		["Fish4"] = "ZZZ_OLDSHOE",
		["Fish5"] = "ZZZ_RUBBERDUCK",
		["Fish6"] = "ZZZ_RUBBERDUCK",
		["Fish7"] = "ZZZ_RUSTYCAN",
		["Fish8"] = "CAVECRAB",
		["Fish9"] = "PIRANHA",
		["Monster1"] = "-",
		["Monster10"] = "-",
		["Monster2"] = "-",
		["Monster3"] = "-",
		["Monster4"] = "-",
		["Monster5"] = "-",
		["Monster6"] = "-",
		["Monster7"] = "-",
		["Monster8"] = "-",
		["Monster9"] = "-",
		["Name"] = "Starrow Subterranean River"}}



-- Got all data, let's now return it!
return ret
