-- This file has be generated by Tricky's MyData
-- 17 Aug 2018; 12:57:26



local ret = {
	["C_WINDVILLE"] = {
		["Dungeon"] = false,
		["Folder"] = "Beaufort",
		["Kthura"] = "TOWN_Windville",
		["Layer"] = "Outside",
		["LocationName"] = "WindVille",
		["LocationPrefix"] = "The City of",
		["Start"] = "Start",
		["UnlockedFromStart"] = false},
	["D_BEAUFORTFOREST"] = {
		["Dungeon"] = true,
		["Folder"] = "Beaufort",
		["Kthura"] = "DUNG_BeaufortForest",
		["Layer"] = "#001",
		["LocationName"] = "Beaufort Forest",
		["LocationPrefix"] = "",
		["Start"] = "Start",
		["UnlockedFromStart"] = true},
	["D_BLACKTOWER"] = {
		["Dungeon"] = true,
		["Folder"] = "Beaufort",
		["Kthura"] = "DUNG_BlackTower",
		["Layer"] = "#000",
		["LocationName"] = "Black Tower",
		["LocationPrefix"] = "The",
		["Start"] = "Start",
		["UnlockedFromStart"] = false},
	["D_FORGOTTENGRAVEYARD"] = {
		["Dungeon"] = true,
		["Folder"] = "Beaufort",
		["Kthura"] = "DUNG_Graveyard",
		["Layer"] = "#005",
		["LocationName"] = "Forgotten Graveyard",
		["LocationPrefix"] = "The",
		["Start"] = "FromWorld",
		["UnlockedFromStart"] = true},
	["D_FREDDY"] = {
		["Dungeon"] = true,
		["Folder"] = "Beaufort",
		["Kthura"] = "DUNG_Freddy",
		["Layer"] = "#001",
		["LocationName"] = "Freddy's Restaurant",
		["LocationPrefix"] = "",
		["Start"] = "Start",
		["UnlockedFromStart"] = false},
	["D_PRIMOSTUNNEL"] = {
		["Dungeon"] = true,
		["Folder"] = "Beaufort",
		["Kthura"] = "DUNG_PrimosTunnel",
		["Layer"] = "#001",
		["LocationName"] = "Primos Tunnel",
		["LocationPrefix"] = "",
		["Start"] = "Start",
		["UnlockedFromStart"] = false},
	["D_STARROW"] = {
		["Dungeon"] = true,
		["Folder"] = "Beaufort",
		["Kthura"] = "DUNG_Starrow",
		["Layer"] = "#001",
		["LocationName"] = "Caves of Starrow",
		["LocationPrefix"] = "The",
		["Start"] = "Start",
		["UnlockedFromStart"] = false}}



-- Got all data, let's now return it!
return ret
