-- File generated by MyData on Saturday 1/12/2018
-- License: << No License information present >>


local ret = {
	["C_PRIMOS"] = {
		["Dungeon"] = true,
		["Folder"] = "PrimosRegion",
		["Kthura"] = "TOWN_Primos",
		["Layer"] = "exterior",
		["LocationName"] = "Primos",
		["LocationPrefix"] = "The village of",
		["Start"] = "Start",
		["UnlockedFromStart"] = true,

	},
	["C_WINDVILLE"] = {
		["Dungeon"] = false,
		["Folder"] = "Beaufort",
		["Kthura"] = "TOWN_Windville",
		["Layer"] = "Outside",
		["LocationName"] = "WindVille",
		["LocationPrefix"] = "The City of",
		["Start"] = "Start",
		["UnlockedFromStart"] = false,

	},
	["D_BEAUFORTFOREST"] = {
		["Dungeon"] = true,
		["Folder"] = "Beaufort",
		["Kthura"] = "DUNG_BeaufortForest",
		["Layer"] = "#001",
		["LocationName"] = "Beaufort Forest",
		["LocationPrefix"] = "",
		["Start"] = "Start",
		["UnlockedFromStart"] = true,

	},
	["D_BLACKTOWER"] = {
		["Dungeon"] = true,
		["Folder"] = "Beaufort",
		["Kthura"] = "DUNG_BlackTower",
		["Layer"] = "#000",
		["LocationName"] = "Black Tower",
		["LocationPrefix"] = "The",
		["Start"] = "Start",
		["UnlockedFromStart"] = false,

	},
	["D_FORGOTTENGRAVEYARD"] = {
		["Dungeon"] = true,
		["Folder"] = "Beaufort",
		["Kthura"] = "DUNG_Graveyard",
		["Layer"] = "#005",
		["LocationName"] = "Forgotten Graveyard",
		["LocationPrefix"] = "The",
		["Start"] = "FromWorld",
		["UnlockedFromStart"] = true,

	},
	["D_FREDDY"] = {
		["Dungeon"] = true,
		["Folder"] = "Beaufort",
		["Kthura"] = "DUNG_Freddy",
		["Layer"] = "#001",
		["LocationName"] = "Freddy's Restaurant",
		["LocationPrefix"] = "",
		["Start"] = "Start",
		["UnlockedFromStart"] = false,

	},
	["D_PRIMOSTUNNEL"] = {
		["Dungeon"] = true,
		["Folder"] = "Beaufort",
		["Kthura"] = "DUNG_PrimosTunnel",
		["Layer"] = "#001",
		["LocationName"] = "Primos Tunnel",
		["LocationPrefix"] = "",
		["Start"] = "Start",
		["UnlockedFromStart"] = false,

	},
	["D_PRIMOSTUNNEL2"] = {
		["Dungeon"] = true,
		["Folder"] = "Beaufort",
		["Kthura"] = "",
		["Layer"] = "#002",
		["LocationName"] = "Primos Tunnel",
		["LocationPrefix"] = "",
		["Start"] = "FromPrimos",
		["UnlockedFromStart"] = true,

	},
	["D_STARROW"] = {
		["Dungeon"] = true,
		["Folder"] = "Beaufort",
		["Kthura"] = "DUNG_Starrow",
		["Layer"] = "#001",
		["LocationName"] = "Caves of Starrow",
		["LocationPrefix"] = "The",
		["Start"] = "Start",
		["UnlockedFromStart"] = false,

	},

}

return ret

